In [13]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]
print('-'*15)
# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])
print(array_2d)
print('-'*15)
# Creating a 3D NumPy array
array_3d = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(array_3d)
print('-'*15)
# Creating another 3D NumPy array based on the 2D one
array_2d3d = np.array([
                        [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]
                        ],

                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                      ])
print(array_2d3d)
print(array_2d3d.shape)


1D Array: [1 2 3 4]
---------------
[[1 2 3 4]
 [5 6 7 8]]
---------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
---------------
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [6]:
array_3d.size

8

In [7]:
array_3d.shape

(2, 2, 2)

In [8]:
array_3d.dtype

dtype('int64')

In [15]:
array_2d3d[0,1,2]

np.int64(7)

In [21]:
array_2d3d[0,:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [22]:
array_2d3d[array_2d3d > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24])

In [26]:
arranged = np.arange(47,92, 2)
arranged

array([47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79,
       81, 83, 85, 87, 89, 91])

In [27]:
new = np.array(array_2d3d)

In [29]:
new[0,1] = [65,64,63,62]

In [30]:
new

array([[[ 1,  2,  3,  4],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [33]:
new[0,0] = 99

In [34]:
new

array([[[99, 99, 99, 99],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [37]:
new[1,:2] = np.array([1,2]).reshape((2,1))

In [41]:
new[1,:2].shape, np.array([1,2]).shape

((2, 4), (2,))

In [38]:
new

array([[[99, 99, 99, 99],
        [65, 64, 63, 62],
        [ 9, 10, 11, 12]],

       [[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [21, 22, 23, 24]]])

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [43]:
a + 5

array([6, 7, 8])

In [44]:
a * 2

array([2, 4, 6])

In [45]:
a * b

array([ 4, 10, 18])

In [46]:
c = np.array([[1,2,3],
              [4,5,6]])
d = np.array([1,1,1])

In [47]:
c + d

array([[2, 3, 4],
       [5, 6, 7]])

In [52]:
e = np.array([1,2]).reshape((1,2))
e + c

ValueError: operands could not be broadcast together with shapes (1,2) (2,3) 

In [51]:
c.shape, e.shape

((2, 3), (2, 1))